#pragma once


#pragma region 文件隐藏用户控制号


#define IOCTL_SET_EXCLUDE_HANDLE      CTL_CODE (FILE_DEVICE_UNKNOWN, (0x900 + 1), METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FS_ADD_FILE             CTL_CODE (FILE_DEVICE_UNKNOWN, (0x900 + 2), METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FS_UPDATE_FILE          CTL_CODE (FILE_DEVICE_UNKNOWN, (0x900 + 3), METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FS_REMOVE_FILE          CTL_CODE (FILE_DEVICE_UNKNOWN, (0x900 + 4), METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FS_ENUM_FILES           CTL_CODE (FILE_DEVICE_UNKNOWN, (0x900 + 5), METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FS_ENABLE_FILE          CTL_CODE (FILE_DEVICE_UNKNOWN, (0x900 + 6), METHOD_BUFFERED, FILE_ANY_ACCESS)

#pragma endregion 文件隐藏用户控制号

#pragma region 文件过滤驱动
NTSTATUS RegisiterFltCallback(PDRIVER_OBJECT DriverObject);
#pragma endregion 文件过滤驱动
